package com.itucity.yjreport.dao.entity;
// default package
// Generated Jan 6, 2014 2:04:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "yjreport", uniqueConstraints = @UniqueConstraint(columnNames = "login_name"))
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4647902043227351243L;
	private String id;
	private String loginName;
	private String password;
	private Date lastLoginDate;
	private String lastLoginIp;
	private byte locked;
	private Date createTime;
	private Date lastUpdate;
	private Byte deleted;
	private Set<UserDetail> userDetails = new HashSet<UserDetail>(0);

	public Users() {
	}

	public Users(String id, String loginName, String password, byte locked,
			Date createTime) {
		this.id = id;
		this.loginName = loginName;
		this.password = password;
		this.locked = locked;
		this.createTime = createTime;
	}

	public Users(String id, String loginName, String password,
			Date lastLoginDate, String lastLoginIp, byte locked,
			Date createTime, Date lastUpdate, Byte deleted, Set<UserDetail> userDetails) {
		this.id = id;
		this.loginName = loginName;
		this.password = password;
		this.lastLoginDate = lastLoginDate;
		this.lastLoginIp = lastLoginIp;
		this.locked = locked;
		this.createTime = createTime;
		this.lastUpdate = lastUpdate;
		this.deleted = deleted;
		this.userDetails = userDetails;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "login_name", unique = true, nullable = false, length = 50)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "password", nullable = false, length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_date", length = 19)
	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	@Column(name = "last_login_ip", length = 15)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	@Column(name = "locked", nullable = false)
	public byte getLocked() {
		return this.locked;
	}

	public void setLocked(byte locked) {
		this.locked = locked;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update", length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "deleted")
	public Byte getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Byte deleted) {
		this.deleted = deleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserDetail> getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(Set<UserDetail> userDetails) {
		this.userDetails = userDetails;
	}

}
